### ISSUE TITLE
No exported PluginModule member from ngxs-api

### ISSUE THREAD

**Issue by perjansson** [amcdnl/ngxs#58]
Trying to follow this guide to add ReduxDevtoolsPluginModule (and LocalStoragePluginModule)
https://amcdnl.gitbooks.io/ngxs/plugins/devtools.html

`import { NgxsModule, ReduxDevtoolsPluginModule } from 'ngxs';` in `app.module.ts`

gives the following typescript compilation error:
`[ts] Module '"/Users/.../node_modules/ngxs/ngxs-api"' has no exported member 'ReduxDevtoolsPluginModule'.`

**Comment by Silthus** [comment]
What I found, is that the documentation does not match the current release. There are a lot of changes and features in the docs that do not work with the current 1.4.8 version. 

It would be great if there is a @next branch or something.

**Comment by st-clair-clarke** [comment]
Please check your imports: ReduxDevtoolsPlugin is impported NOT ReduxDevtoolsPluginModule

import {
  LocalStoragePlugin, LoggerPlugin, Ngxs, NgxsModule, ReduxDevtoolsPlugin
} from 'ngxs'

@NgModule(
    {
      declarations: [
        ...
      ],
      imports: [,
        NgxsModule.forRoot( [
            ClerkingStore,
            RegistrationStore, RsStore ], {
          plugins: [
            LocalStoragePlugin,
            ReduxDevtoolsPlugin.forRoot(
                {// Set to true for prod mode
                  disabled: environment.production ? true : false
                } )]
        } )
      ],
      entryComponents: [],
      providers: [
      ],
     
      bootstrap: [ AppComponent ],
      schemas: [ NO_ERRORS_SCHEMA ]
    } )
export class AppModule {
  constructor(){  }
}


Hope this helps. It is what has been working for me.

**Comment by st-clair-clarke** [comment]
Have to agree with @Silthus about the docs. But I would suggest patients. Most times an author of an open source software has a fulltime job and cannot do all that is necessary for the open source as its users' might demand.

I think the new offering should catch-up with the docs. 2 days ago that author mentioned that he should have an updated version in a 'few days'.

**Comment by perjansson** [comment]
Thx @st-clair-clarke, it worked with that configuration.

**Comment by st-clair-clarke** [comment]
Glad to be of some help @perjansson.

**Comment by amcdnl** [comment]
Oh, Im sorry about that. We haven't cut a new release with that. I'm going to cut that now.

**Comment by st-clair-clarke** [comment]
@perjansson @amcdnl The above solution is now broken in current release "ngxs": "^1.5.1", Worked in "ngxs": "^1.4.8",

Given the following in AppModule imports

```
        NgxsModule.forRoot(  [  ClerkingStore,   RegistrationStore ] ),
        ReduxDevtoolsPluginModule.forRoot(
            {// Set to true for prod mode
              disabled: environment.production ? true : false
            } )//]
```

...
I am getting the following errors

```
compiler.js:492 Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:492)
    at eval (compiler.js:15254)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15229)
    at JitCompiler._loadModules (compiler.js:35487)
    at JitCompiler._compileModuleAndComponents (compiler.js:35448)
    at JitCompiler.compileModuleAsync (compiler.js:35342)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:239)
    at PlatformRef.bootstrapModule (core.js:5551)
    at eval (main.ts:52)
```

The application fails to load.

Removing

 ```
    ReduxDevtoolsPluginModule.forRoot(
            {// Set to true for prod mode
              disabled: environment.production ? true : false
            } )//]
```

the application loads normally but without devtool support.

Could you please reopen @perjansson ?

Cheers

**Comment by perjansson** [comment]
That’s true @st-clair-clarke, I got similar error. Reopening...

**Comment by deebloo** [comment]
@perjansson it should be ReduxDevtoolsPlugin, LocalStoragePluginModule and LoggerPluginModule

**Comment by st-clair-clarke** [comment]
With the following:

**Comment by xmlking** [comment]
Looking for docs on same issue

**Comment by deebloo** [comment]
@st-clair-clarke may be the docs are wrong. ReduxDevtoolsPlugin should be ReduxDevtoolsPluginModule

**Comment by deebloo** [comment]
@perjansson the current seem to be up to date. https://amcdnl.gitbooks.io/ngxs/content/plugins/devtools.html

**Comment by deebloo** [comment]
@perjansson can you confirm if the same issue persists with the current documentation and the latest version?

**Comment by amcdnl** [comment]
Gitbook has crazy aggressive caching...

**Comment by st-clair-clarke** [comment]
Note that @deebloo that your suggestion is exactly what I did when I got the errors above; so neither works. Could someone test the ReduxDevtoolsPluginModule actually works. IT is not working for us.

The other thing is I am using these in my AppModule, but I note that at the link above by you MyModule is used. Does this means that I should import and re-export in MyModule.

Cheers

**Comment by amcdnl** [comment]
@deebloo - I fixed the devtools, it was returning the wrong object as the module. Problem is now the devtools isn't even getting wired up. Can you take a look ASAP?

**Comment by amcdnl** [comment]
Fixed in 1.5.2

**Comment by st-clair-clarke** [comment]
@amcdnl I am no longer getting any errors from the dev tool plugin version 1.5.2, but now there is no state in the dev tool UI. Maybe the dev tool showing the previous state is fixed but now the dev tool window shows undefined state. The logger shows normally in the console.

Should we continue on this thread or open a new thread for this issue?

Cheers

**Comment by st-clair-clarke** [comment]
I actually remove node_modules directory and 'yarn' my directory with the same result - state is definitely undefined in the UI tree. However, all my states are logged as expected.

**Comment by perjansson** [comment]
This code works for me now since 1.5.3:

```
NgxsModule.forRoot([AppStore]),
ReduxDevtoolsPluginModule.forRoot({ disabled: isProduction }),
LocalStoragePluginModule.forRoot({
	key: STORAGE_KEY_NGXS_STORE,
	serialize: JSON.stringify,
	strategy: StorageStrategy.sessionStorage,
	deserialize: JSON.parse,
})
```

**Comment by st-clair-clarke** [comment]
@perjansson Are you seeing the state in the Redux UI, For me the events do appear but the state is still undefined.

Below is my code with no state visualized in the redux uI

```
       NgxsModule.forRoot(
            [
              ClerkingStore,
              RegistrationStore,
              RsStore ]),

        ReduxDevtoolsPluginModule.forRoot(
            {
              disabled: false //environment.production ? false : true
            } ),
        LocalStoragePluginModule.forRoot(
            {
              key: '@@STATE',
              serialize: JSON.stringify,
              strategy: StorageStrategy.sessionStorage,
              deserialize: JSON.parse
            } ),
        LoggerPluginModule.forRoot(
            {
              logger: console,
              collapsed: true
            } )
```

Let me know what you think. See the graphic below

[dev-tool.pdf](https://github.com/amcdnl/ngxs/files/1808753/dev-tool.pdf)

Cheers

**Comment by perjansson** [comment]
Yes @st-clair-clarke, Redux dev tool is working displaying all event names, states, state changes and diffs. The only thing not working is that I don't see the payload of the action, but the state still updates correctly.

**Comment by st-clair-clarke** [comment]
@perjansson The screenshot aboe (dev-tool.pdf) says otherwise at my end. Do you see an error in my code above? I will double check.

**Comment by perjansson** [comment]
@st-clair-clarke Your app.module looks like mine except that LoggerPluginModule is not working for me, it fails with an exception, so I've removed it. Before updating to 1.5.3 I deleted node_modules folder but I think you mentioned that also had done that.

**Comment by st-clair-clarke** [comment]
@perjansson Interesting. I remove the working LoggerPluginModule and now the redux UI is working! So it seems that LoggerPluginModule might have an issue. Maybe you should open a new thread. Thanks for the observation.

**Comment by RobCannon** [comment]
I am getting the message:
ERROR in Error during template compile of 'AppModule'
Function calls are not supported in decorators but 'ReduxDevtoolsPluginModule' was called.

When using this with the --aot flag
```
@NgModule({
  declarations: [AppComponent, TopMenuComponent],
  imports: [
    CommonModule,
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    NgxsModule.forRoot([]),
    ReduxDevtoolsPluginModule.forRoot({
      disabled: environment.production
    })
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by st-clair-clarke** [comment]
@RobCannon Try giving the NgxModule something to display and see what happens. Currently you have an empty array (NgxsModule.forRoot([]), Somthing like: 

` NgxsModule.forRoot( [RsStore ])`

**Comment by RobCannon** [comment]
All of my stores are defined in features and I don't have a store for the root module.  Also, this is a compile time error, so I doubt that anything passed in the previous line would have an impact.

But, just in case, I created a simple store for the root module, verified that everything still work without --aot.  When I enable the --aot flag, I still get the same error:

ERROR in Error during template compile of 'AppModule'
Function calls are not supported in decorators but 'ReduxDevtoolsPluginModule' was called.

I am using angular-cli 1.7.3 and the matching typescript 2.6.2
